---
title: "Kolos 1"
author: "Paweł Benkowski"
date: "27 10 2020"
output: html_document
---
```{r}
install.packages('tidyverse')
install.packages('devtools')
library(tidyverse)
library(devtools)
```
Zadanie 1
```{r}
# Dane
doch_tys = c(1.71, 2.98, 3.4, 2.17, 1.42)
comps = c('A', 'B', 'C', 'D', 'E')
df = data.frame(comps, doch_tys)

# 1
ggplot(data = df, mapping = aes(x = comps, y = doch_tys)) +
  geom_point()
# 2
x_mean = mean(x)
x_round = round(mean(x), 2)
cat("Średnia z próby wynosi ", x_mean, "~=", x_round)
# 3
ggplot(data = df, mapping = aes(x = comps, y = doch_tys)) +
  geom_abline(intercept = x_mean, slope=0) +
  geom_linerange(aes(ymin=doch_tys - x_mean, ymax=x_mean))
  geom_point()


s_kwadrat = var(x)
sigma_kwadrat = var(x) * 4/5
# Var to estymator wariancji - liczy ten s2
# liczy tym wzorem bo jest bardziej praktyczny
s = sd(x)
# print(s)
sigma = sd(x) * sqrt(4/5)
# print(sigma)
wspolczynnik_zmiennosci = sigma / x_mean
# print(wspolczynnik_zmiennosci * 100, '%')
dane = c(3.84, 7.07, 6.86, 5.38, 4.41, 6.61, 6.39, 7.62, 3.4, 5.18, 3.6, 7.02)
hist(dane)
sort(dane)
i = .25 * 12
j = i + 1
# 3.84 i 4.41
q_1 = 3.84 + .25 * (4.41 - 3.84)
print(q_1)
me = 3.84 + .50 * (4.41 - 3.84)
print(me)
q_3 = 3.84 + .75 * (4.41 - 3.84)
print(q_3)
quantile(dane, 0.25, type=6)
# domyslnie jest typ 7
```
Zadanie 7
```{r}


```

