runtime: python37
instance_class: F1

handlers:
    - url: /home
      static_files: index.html
      upload: index.html

    - url: /.*
      script: auto


automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_instances: 0
  max_instances: 2
    
    
    
