runtime: python37
instance_class: F1

service: projekt

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_instances: 0
  max_instances: 2
    
    
    
