# Generated by Django 3.1.7 on 2021-03-18 17:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
                ('country_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EU', 'Europe'), ('AT', 'Austria'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('N', 'Norway'), ('S', 'Switzerland'), ('BE', 'Belgium')], max_length=5), size=None)),
            ],
        ),
    ]
