# Generated by Django 3.1.7 on 2021-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(choices=[('EU', 'Europe'), ('AT', 'Austria'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('N', 'Norway'), ('S', 'Switzerland'), ('BE', 'Belgium')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='country_codes',
        ),
    ]
