# Generated by Django 3.1.7 on 2021-03-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210319_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.ManyToManyField(to='core.Country'),
        ),
    ]
