version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s"
    datefmt: "%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: standard
    filename: ./tmp/warnings.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

root: # Loggers are organized in hierarchy this is the root logger
  level: ERROR
  handlers: [console, file]

loggers: # Descendants of root logger
  mymodule: # Logger for mymodule
    level: INFO
    handlers: [file]
    propagate: no # won't propagate to root
