version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=p455WORDC#
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p455WORDC#
